#!/usr/bin/env python3
"""Renders the mantle globe from hyperlight-site's components/studies/mantle.tsx as a static
SVG: the same geometry, gradients, masks and lighting, at the component's initial frame
(time 0, the pose it renders on the server). Run from this directory:

    python3 render-globe.py > mantle-globe.svg
"""
import math

PI = math.pi
RADIUS = 207
STRATA = 34
CONTOURS = 69
STRATA_RADII = [83 + (i * (RADIUS - 83)) / (STRATA - 1) for i in range(STRATA)]
ORBIT_SECONDS = 28
CUT_LONGITUDE = -0.29
TILT = -PI / 4
TIME = 0.0


def fixed(v):
    return f"{v:.2f}"


def coordinate(p):
    return f"{fixed(p[0])},{fixed(p[1])}"


def phase(t):
    return (t / ORBIT_SECONDS) * PI * 2


def stratum_light(index, t):
    light = 0.5 + 0.5 * math.sin(index * 0.59 - t * 0.75)
    return f"{0.16 + light * light * 0.4:.4f}"


def project(x, y, z):
    return (320 + x * math.cos(TILT) - y * math.sin(TILT),
            302 + x * math.sin(TILT) + y * math.cos(TILT), z)


def visible_line(points, side):
    d = ""
    drawing = False
    inside = (lambda p: p[2] >= 0) if side == "front" else (lambda p: p[2] < 0)
    for i, current in enumerate(points):
        previous = points[i - 1] if i > 0 else None
        if previous is not None and inside(previous) != inside(current):
            t = previous[2] / (previous[2] - current[2])
            crossing = (previous[0] + (current[0] - previous[0]) * t,
                        previous[1] + (current[1] - previous[1]) * t, 0)
            d += ("L" if drawing else "M") + coordinate(crossing)
            drawing = inside(current)
        if inside(current):
            d += ("L" if drawing else "M") + coordinate(current)
            drawing = True
        else:
            drawing = False
    return d or "M320,302"


def point(latitude, longitude, radius, t):
    turn = longitude + phase(t)
    x = radius * math.cos(latitude) * math.sin(turn)
    y = radius * math.sin(latitude)
    return project(x, y, radius * math.cos(latitude) * math.cos(turn))


def shell(t, left, right):
    pts = [point(-PI / 2 + (i / 100) * PI, left, RADIUS, t) for i in range(101)]
    pts += [point(-PI / 2 + (i / 100) * PI, right, RADIUS, t) for i in range(100, -1, -1)]
    return "M" + "L".join(coordinate(p) for p in pts) + "Z"


def meridian(radius, longitude, t):
    return [point(-PI / 2 + (i / 100) * PI, longitude, radius, t) for i in range(101)]


def contour(index, t):
    latitude = -PI / 2 + ((index + 1) / (CONTOURS + 1)) * PI
    pts = []
    for i in range(91):
        longitude = 1.3 + (i / 90) * (PI * 2 + CUT_LONGITUDE - 1.3)
        relief = (math.sin(longitude * 4.1 + latitude * 7) * 0.024 +
                  math.sin(longitude * 9 - latitude * 12) * 0.009) * math.cos(latitude)
        pts.append(point(latitude + relief, longitude, RADIUS, t))
    return pts


def surface(t, side):
    turn = math.fmod(phase(t), PI * 2)
    start = 1.3 + turn
    end = PI * 2 + CUT_LONGITUDE + turn
    d = ""
    for k in range(-1, 3):
        horizon = (-PI / 2 if side == "front" else PI / 2) + k * PI * 2
        left = max(start, horizon)
        right = min(end, horizon + PI)
        if right > left:
            d += shell(0, left, right)
    return d or "M320,302Z"


def frame(t):
    contours = [contour(i, t) for i in range(CONTOURS)]
    meridians = [meridian(RADIUS, 1.3 + (i / 24) * (PI * 2 + CUT_LONGITUDE - 1.3), t) for i in range(25)]
    seams = [meridian(RADIUS - (i % 3) * 2.1, CUT_LONGITUDE if i < 3 else 1.3, t) for i in range(6)]

    def layer(side):
        return {
            "shell": surface(t, side),
            "contours": "".join(visible_line(p, side) for p in contours),
            "meridians": "".join(visible_line(p, side) for p in meridians),
            "seams": [visible_line(p, side) for p in seams],
        }
    return {"back": layer("back"), "front": layer("front")}


def main():
    f = frame(TIME)
    out = []
    w = out.append
    w('<svg xmlns="http://www.w3.org/2000/svg" viewBox="96 78 448 496" width="224" height="248" '
      'fill="none" role="img" aria-labelledby="title desc">')
    w('<title id="title">Mantle</title>')
    w('<desc id="desc">A globe of engraved stone with a wedge cut away, showing densely '
      'layered strata lit in a soft spectrum around a stone core.</desc>')
    w('<!-- Generated by render-globe.py from hyperlight-site components/studies/mantle.tsx, time 0. -->')
    w('<defs>')
    w(f'<radialGradient id="stone" gradientUnits="userSpaceOnUse" cx="{320 - RADIUS + 0.28 * RADIUS * 2:g}" '
      f'cy="{302 - RADIUS + 0.2 * RADIUS * 2:g}" r="{0.86 * RADIUS * 2:g}">'
      '<stop stop-color="#667071"/><stop offset=".26" stop-color="#353e40"/>'
      '<stop offset=".62" stop-color="#151c20"/><stop offset=".91" stop-color="#0b1013"/>'
      '<stop offset="1" stop-color="#384246"/></radialGradient>')
    w('<radialGradient id="section" cx=".38" cy=".31" r=".76">'
      '<stop stop-color="#4b5252"/><stop offset=".25" stop-color="#242d31"/>'
      '<stop offset=".48" stop-color="#354044"/><stop offset=".51" stop-color="#12191c"/>'
      '<stop offset=".69" stop-color="#414647"/><stop offset=".72" stop-color="#171e21"/>'
      '<stop offset=".9" stop-color="#2c3437"/><stop offset="1" stop-color="#131a1e"/></radialGradient>')
    w('<radialGradient id="core" cx=".33" cy=".25" r=".8">'
      '<stop stop-color="#92998e"/><stop offset=".23" stop-color="#596461"/>'
      '<stop offset=".61" stop-color="#2c383b"/><stop offset=".9" stop-color="#1b252b"/>'
      '<stop offset="1" stop-color="#586263"/></radialGradient>')
    w('<linearGradient id="spectrum" x1="168" y1="132" x2="491" y2="468" gradientUnits="userSpaceOnUse">'
      '<stop stop-color="#aac7bb"/><stop offset=".23" stop-color="#91bbd0"/>'
      '<stop offset=".48" stop-color="#b1a3c6"/><stop offset=".73" stop-color="#c1a6ad"/>'
      '<stop offset="1" stop-color="#c7b48d"/></linearGradient>')
    w('<linearGradient id="engraving" x1="181" y1="154" x2="446" y2="451" gradientUnits="userSpaceOnUse">'
      '<stop stop-color="#c4d0cc" stop-opacity=".36"/><stop offset=".46" stop-color="#a0b3b8" stop-opacity=".2"/>'
      '<stop offset="1" stop-color="#849898" stop-opacity=".06"/></linearGradient>')
    w('<radialGradient id="shadow"><stop stop-color="#819a9d" stop-opacity=".1"/>'
      '<stop offset="1" stop-color="#819a9d" stop-opacity="0"/></radialGradient>')
    w(f'<clipPath id="globe"><circle cx="320" cy="302" r="{RADIUS}"/></clipPath>')
    w(f'<radialGradient id="rear-visibility" gradientUnits="userSpaceOnUse" cx="320" cy="302" r="{RADIUS}">'
      '<stop stop-color="white" stop-opacity=".28"/><stop offset=".75" stop-color="white" stop-opacity=".4"/>'
      '<stop offset="1" stop-color="white"/></radialGradient>')
    w(f'<mask id="rear-ink" maskUnits="userSpaceOnUse" x="0" y="0" width="640" height="640">'
      f'<circle cx="320" cy="302" r="{RADIUS}" fill="url(#rear-visibility)"/></mask>')
    w('<mask id="behind-core" maskUnits="userSpaceOnUse" x="0" y="0" width="640" height="640">'
      '<rect width="640" height="640" fill="white"/><circle cx="320" cy="302" r="82.5" fill="black"/></mask>')
    w('</defs>')
    w('<ellipse cx="320" cy="541" rx="164" ry="23" fill="url(#shadow)"/>')
    w(f'<circle cx="320" cy="302" r="{RADIUS}" fill="url(#section)"/>')
    w('<g clip-path="url(#globe)">')

    def layer(side):
        opacity = 0.62 if side == "front" else 0.32
        w(f'<g><path d="{f[side]["shell"]}" fill="url(#stone)" fill-opacity="{opacity}"/></g>')

    def rims(side):
        w('<g mask="url(#behind-core)">' if side == "back" else '<g>')
        w('<g mask="url(#rear-ink)">' if side == "back" else '<g>')
        w(f'<path d="{f[side]["contours"]}" stroke="url(#engraving)" stroke-width=".65"/>')
        w(f'<path d="{f[side]["meridians"]}" stroke="#acbbb9" stroke-width=".45" stroke-opacity=".095"/>')
        w('</g>')
        w('<g stroke="url(#spectrum)">')
        for i, d in enumerate(f[side]["seams"]):
            longitude = CUT_LONGITUDE if i < 3 else 1.3
            light = 0.72 + 0.28 * math.cos(longitude + phase(TIME))
            opacity = (0.7 - (i % 3) * 0.18) * light
            w(f'<path d="{d}" stroke-width="{1.4 - (i % 3) * 0.3:.2f}" opacity="{opacity:.4f}"/>')
        w(f'<path d="{f[side]["seams"][0]}" stroke-width="2" stroke-dasharray="61 610" '
          f'stroke-dashoffset="0" stroke-linecap="round" opacity="{0.72 + 0.28 * math.cos(CUT_LONGITUDE):.4f}"/>')
        w('</g></g>')

    layer("back")
    w('<g stroke="url(#spectrum)" stroke-width=".65">')
    for i, r in enumerate(STRATA_RADII):
        w(f'<circle cx="320" cy="302" r="{r:.4f}" opacity="{stratum_light(i, TIME)}"/>')
    w('</g>')
    w('<circle cx="320" cy="302" r="82" fill="url(#core)" stroke="#9ba9aa" stroke-width=".65" stroke-opacity=".3"/>')
    w('<g stroke="#8faaa7" stroke-opacity=".14" stroke-width=".5">')
    for i in range(15):
        w(f'<circle cx="320" cy="302" r="{fixed(36 + i * 3.12)}"/>')
    w('</g>')
    layer("front")
    rims("back")
    rims("front")
    w('</g>')
    w(f'<circle cx="320" cy="302" r="{RADIUS}" stroke="url(#engraving)" stroke-width=".9"/>')
    w('<path d="M316 557h8m-4-4v8" stroke="#829395" stroke-width=".6" opacity=".4"/>')
    w('</svg>')
    print("\n".join(out))


if __name__ == "__main__":
    main()
