#!/usr/bin/env python3
"""Draws mantle's README mark: the site's globe (components/studies/mantle.tsx) reduced to a
two-tone vector in the style of the focal, slates and vorpal marks. A sphere cut open along
a seam: its stone surface a solid crescent with contour lines cut through it, and strata
rings around a solid core. The palettes are vorpal's: primary ink plus a mid-grey that
reads on either background. Run from this directory:

    python3 render-mark.py
"""
import math

C = 100.0          # centre of the 200-unit square
R = 86.0           # sphere radius
B = 36.0           # half-width of the seam's great-circle ellipse
U = (1 / math.sqrt(2), 1 / math.sqrt(2))     # seam runs top-left to bottom-right
TL = (C - R * U[0], C - R * U[1])
BR = (C + R * U[0], C + R * U[1])

PALETTES = {
    "light": ("#1f2328", "#8e9399"),
    "dark": ("#f0f6fc", "#7c8794"),
}


def pt(p):
    return f"{p[0]:.2f} {p[1]:.2f}"


def half_ellipse(b):
    """The lower-left half of a great circle whose projection has half-width b."""
    return f"M {pt(TL)} A {R:.2f} {b:.2f} 45 0 0 {pt(BR)}"


def svg(ink, stone):
    surface = f"{half_ellipse(B)} A {R:.2f} {R:.2f} 0 0 1 {pt(TL)} Z"
    contours = " ".join(half_ellipse(b) for b in (52.0, 67.0))
    rings = "".join(
        f'<circle cx="{C:g}" cy="{C:g}" r="{r:g}"/>' for r in (38, 51, 64)
    )
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 200 200" role="img" aria-labelledby="title desc">
  <title id="title">Mantle</title>
  <desc id="desc">A globe cut open along a seam: its stone surface on one side, strata rings around a solid core on the other.</desc>
  <!-- Generated by render-mark.py. Sphere radius {R:g} about ({C:g}, {C:g}); the seam is the
       lower-left half of a great circle along the diagonal, half-width {B:g}. The surface
       crescent is solid, with its contour lines cleared by a mask. -->
  <defs>
    <clipPath id="sphere"><circle cx="{C:g}" cy="{C:g}" r="{R:g}"/></clipPath>
    <mask id="contours" maskUnits="userSpaceOnUse" x="0" y="0" width="200" height="200">
      <rect width="200" height="200" fill="#ffffff"/>
      <path d="{contours}" fill="none" stroke="#000000" stroke-width="5"/>
    </mask>
    <mask id="interior" maskUnits="userSpaceOnUse" x="0" y="0" width="200" height="200">
      <rect width="200" height="200" fill="#ffffff"/>
      <path d="{surface}" fill="#000000"/>
    </mask>
  </defs>
  <g clip-path="url(#sphere)">
    <path d="{surface}" fill="{stone}" mask="url(#contours)"/>
    <g mask="url(#interior)" fill="none" stroke="{ink}" stroke-width="6">
      {rings}
    </g>
    <circle cx="{C:g}" cy="{C:g}" r="24" fill="{ink}"/>
  </g>
  <g fill="none" stroke="{ink}" stroke-linecap="round" stroke-width="7">
    <path d="{half_ellipse(B)}"/>
    <circle cx="{C:g}" cy="{C:g}" r="{R:g}"/>
  </g>
</svg>
'''


for name, (ink, stone) in (("mantle-mark.svg", PALETTES["light"]),
                           ("mantle-mark-light.svg", PALETTES["light"]),
                           ("mantle-mark-dark.svg", PALETTES["dark"])):
    with open(name, "w") as f:
        f.write(svg(ink, stone))
