#!/usr/bin/env python3
"""Draws mantle's README mark: the site's globe (components/studies/mantle.tsx) reduced to a
one-colour vector in the style of the focal, slates and vorpal marks. A sphere, its stone
surface a translucent crescent crossed by contour lines, cut open along a seam to show
strata rings around a solid core. Run from this directory:

    python3 render-mark.py
"""
import math

C = 100.0          # centre of the 200-unit square
R = 86.0           # sphere radius
B = 36.0           # half-width of the seam's great-circle ellipse
U = (1 / math.sqrt(2), 1 / math.sqrt(2))     # seam runs top-left to bottom-right
TL = (C - R * U[0], C - R * U[1])
BR = (C + R * U[0], C + R * U[1])


def pt(p):
    return f"{p[0]:.2f} {p[1]:.2f}"


def half_ellipse(b):
    """The lower-left half of a great circle whose projection has half-width b."""
    return f"M {pt(TL)} A {R:.2f} {b:.2f} 45 0 0 {pt(BR)}"


def svg(color):
    surface = f"{half_ellipse(B)} A {R:.2f} {R:.2f} 0 0 1 {pt(TL)} Z"
    contours = " ".join(half_ellipse(b) for b in (52.0, 66.0, 78.0))
    rings = "".join(
        f'<circle cx="{C:g}" cy="{C:g}" r="{r:g}" stroke-opacity="{o}"/>'
        for r, o in ((36, 0.95), (47, 0.8), (58, 0.65), (69, 0.5), (79, 0.35))
    )
    return f'''<svg xmlns="http://www.w3.org/2000/svg" width="90" height="90" viewBox="0 0 200 200" role="img" aria-labelledby="title desc">
  <title id="title">Mantle</title>
  <desc id="desc">A globe cut open along a seam: its stone surface on one side, strata rings around a solid core on the other.</desc>
  <!-- Generated by render-mark.py. Sphere radius {R:g} about ({C:g}, {C:g}); the seam is the
       lower-left half of a great circle with its axis along the diagonal and half-width {B:g}. -->
  <defs>
    <clipPath id="sphere"><circle cx="{C:g}" cy="{C:g}" r="{R:g}"/></clipPath>
    <clipPath id="surface"><path d="{surface}"/></clipPath>
    <mask id="interior" maskUnits="userSpaceOnUse" x="0" y="0" width="200" height="200">
      <circle cx="{C:g}" cy="{C:g}" r="{R:g}" fill="#ffffff"/>
      <path d="{surface}" fill="#000000"/>
    </mask>
  </defs>
  <g clip-path="url(#sphere)">
    <path d="{surface}" fill="{color}" fill-opacity="0.16"/>
    <g clip-path="url(#surface)" fill="none" stroke="{color}" stroke-width="3" stroke-opacity="0.4">
      <path d="{contours}"/>
    </g>
    <g mask="url(#interior)" fill="none" stroke="{color}" stroke-width="3.5">
      {rings}
    </g>
    <circle cx="{C:g}" cy="{C:g}" r="24" fill="{color}"/>
  </g>
  <g fill="none" stroke="{color}" stroke-linecap="round">
    <path d="{half_ellipse(B)}" stroke-width="6"/>
    <circle cx="{C:g}" cy="{C:g}" r="{R:g}" stroke-width="6"/>
  </g>
</svg>
'''


for name, color in (("mantle-mark.svg", "#1f2328"), ("mantle-mark-light.svg", "#1f2328"),
                    ("mantle-mark-dark.svg", "#f0f6fc")):
    with open(name, "w") as f:
        f.write(svg(color))
