//! S3's actions and condition keys, as the Service Authorization Reference's S3
//! document, version v1.4, lists them (docs/research/17 §5). Written by
//! `scripts/s3-actions.py` from `tests/data/sar-s3.json`, which `tests/sar_catalog.rs`
//! checks it against.

use super::{Action, KeyType, Kind};

/// The actions that act on a bucket or an object, which a bucket policy can name, in
/// the order of their names without regard to case.
pub const ACTIONS: [Action; 106] = [
    Action {
        name: "AbortMultipartUpload",
        kind: Kind::Object,
        keys: &[
            "s3:AccessGrantsInstanceArn",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "AllowVendedLogDeliveryForResource",
        kind: Kind::Bucket,
        keys: &[
            "s3:deliverySourceArn",
            "s3:logType",
            "s3:resourceArnBeingAuthorized",
        ],
    },
    Action {
        name: "BypassGovernanceRetention",
        kind: Kind::Object,
        keys: &[
            "s3:RequestObjectTag/<key>",
            "s3:RequestObjectTagKeys",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-acl",
            "s3:x-amz-content-sha256",
            "s3:x-amz-copy-source",
            "s3:x-amz-grant-full-control",
            "s3:x-amz-grant-read",
            "s3:x-amz-grant-read-acp",
            "s3:x-amz-grant-write",
            "s3:x-amz-grant-write-acp",
            "s3:x-amz-metadata-directive",
            "s3:x-amz-server-side-encryption",
            "s3:x-amz-server-side-encryption-aws-kms-key-id",
            "s3:x-amz-server-side-encryption-customer-algorithm",
            "s3:x-amz-storage-class",
            "s3:x-amz-website-redirect-location",
        ],
    },
    Action {
        name: "CreateBucket",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:locationconstraint",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-acl",
            "s3:x-amz-bucket-namespace",
            "s3:x-amz-content-sha256",
            "s3:x-amz-grant-full-control",
            "s3:x-amz-grant-read",
            "s3:x-amz-grant-read-acp",
            "s3:x-amz-grant-write",
            "s3:x-amz-grant-write-acp",
            "s3:x-amz-object-ownership",
        ],
    },
    Action {
        name: "CreateBucketMetadataTableConfiguration",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "DeleteBucket",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "DeleteBucketMetadataTableConfiguration",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "DeleteBucketPolicy",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "DeleteBucketWebsite",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "DeleteObject",
        kind: Kind::Object,
        keys: &[
            "s3:AccessGrantsInstanceArn",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:if-match",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "DeleteObjectAnnotation",
        kind: Kind::Object,
        keys: &[
            "s3:ExistingObjectTag/<key>",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
            "s3:x-amz-object-if-match",
        ],
    },
    Action {
        name: "DeleteObjectTagging",
        kind: Kind::Object,
        keys: &[
            "s3:ExistingObjectTag/<key>",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "DeleteObjectVersion",
        kind: Kind::Object,
        keys: &[
            "s3:AccessGrantsInstanceArn",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:versionid",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "DeleteObjectVersionAnnotation",
        kind: Kind::Object,
        keys: &[
            "s3:ExistingObjectTag/<key>",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:versionid",
            "s3:x-amz-content-sha256",
            "s3:x-amz-object-if-match",
        ],
    },
    Action {
        name: "DeleteObjectVersionTagging",
        kind: Kind::Object,
        keys: &[
            "s3:ExistingObjectTag/<key>",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:versionid",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetAccelerateConfiguration",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetAnalyticsConfiguration",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetBucketAbac",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetBucketAcl",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetBucketCORS",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetBucketLocation",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetBucketLogging",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetBucketMetadataTableConfiguration",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetBucketNotification",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetBucketObjectLockConfiguration",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:signatureversion",
        ],
    },
    Action {
        name: "GetBucketOwnershipControls",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetBucketPolicy",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetBucketPolicyStatus",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetBucketPublicAccessBlock",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetBucketRequestPayment",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetBucketTagging",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetBucketVersioning",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetBucketWebsite",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetEncryptionConfiguration",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetIntelligentTieringConfiguration",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetInventoryConfiguration",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetLifecycleConfiguration",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetMetricsConfiguration",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetObject",
        kind: Kind::Object,
        keys: &[
            "s3:AccessGrantsInstanceArn",
            "s3:ExistingObjectTag/<key>",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetObjectAcl",
        kind: Kind::Object,
        keys: &[
            "s3:AccessGrantsInstanceArn",
            "s3:ExistingObjectTag/<key>",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetObjectAnnotation",
        kind: Kind::Object,
        keys: &[
            "s3:ExistingObjectTag/<key>",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetObjectAttributes",
        kind: Kind::Object,
        keys: &[
            "s3:ExistingObjectTag/<key>",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetObjectLegalHold",
        kind: Kind::Object,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetObjectRetention",
        kind: Kind::Object,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetObjectTagging",
        kind: Kind::Object,
        keys: &[
            "s3:ExistingObjectTag/<key>",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetObjectTorrent",
        kind: Kind::Object,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetObjectVersion",
        kind: Kind::Object,
        keys: &[
            "s3:AccessGrantsInstanceArn",
            "s3:ExistingObjectTag/<key>",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:versionid",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetObjectVersionAcl",
        kind: Kind::Object,
        keys: &[
            "s3:AccessGrantsInstanceArn",
            "s3:ExistingObjectTag/<key>",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:versionid",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetObjectVersionAnnotation",
        kind: Kind::Object,
        keys: &[
            "s3:ExistingObjectTag/<key>",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:versionid",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetObjectVersionAnnotationForReplication",
        kind: Kind::Object,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetObjectVersionAttributes",
        kind: Kind::Object,
        keys: &[
            "s3:ExistingObjectTag/<key>",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:versionid",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetObjectVersionForReplication",
        kind: Kind::Object,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetObjectVersionTagging",
        kind: Kind::Object,
        keys: &[
            "s3:ExistingObjectTag/<key>",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:versionid",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetObjectVersionTorrent",
        kind: Kind::Object,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:versionid",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "GetReplicationConfiguration",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "InitiateReplication",
        kind: Kind::Object,
        keys: &["s3:ResourceAccount"],
    },
    Action {
        name: "ListBucket",
        kind: Kind::Bucket,
        keys: &[
            "s3:AccessGrantsInstanceArn",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:delimiter",
            "s3:max-keys",
            "s3:prefix",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "ListBucketMultipartUploads",
        kind: Kind::Bucket,
        keys: &[
            "s3:AccessGrantsInstanceArn",
            "s3:AccessPointNetworkOrigin",
            "s3:AccessPointTag/${TagKey}",
            "s3:DataAccessPointAccount",
            "s3:DataAccessPointArn",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "ListBucketVersions",
        kind: Kind::Bucket,
        keys: &[
            "s3:AccessGrantsInstanceArn",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:delimiter",
            "s3:max-keys",
            "s3:prefix",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "ListMultipartUploadParts",
        kind: Kind::Object,
        keys: &[
            "s3:AccessGrantsInstanceArn",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "ListObjectAnnotations",
        kind: Kind::Object,
        keys: &[
            "s3:ExistingObjectTag/<key>",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:annotation-prefix",
            "s3:authType",
            "s3:max-annotation-results",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "ListObjectVersionAnnotations",
        kind: Kind::Object,
        keys: &[
            "s3:ExistingObjectTag/<key>",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:annotation-prefix",
            "s3:authType",
            "s3:max-annotation-results",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:versionid",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "ListTagsForResource",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "ObjectOwnerOverrideToBucketOwner",
        kind: Kind::Object,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "PauseReplication",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:destinationRegion",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "PutAccelerateConfiguration",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "PutAnalyticsConfiguration",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "PutBucketAbac",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "PutBucketAcl",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-acl",
            "s3:x-amz-content-sha256",
            "s3:x-amz-grant-full-control",
            "s3:x-amz-grant-read",
            "s3:x-amz-grant-read-acp",
            "s3:x-amz-grant-write",
            "s3:x-amz-grant-write-acp",
        ],
    },
    Action {
        name: "PutBucketCORS",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "PutBucketLogging",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "PutBucketNotification",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "PutBucketObjectLockConfiguration",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
        ],
    },
    Action {
        name: "PutBucketOwnershipControls",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "PutBucketPolicy",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "PutBucketPublicAccessBlock",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "PutBucketRequestPayment",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "PutBucketTagging",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "PutBucketVersioning",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "PutBucketWebsite",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "PutEncryptionConfiguration",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "PutIntelligentTieringConfiguration",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "PutInventoryConfiguration",
        kind: Kind::Bucket,
        keys: &[
            "s3:InventoryAccessibleOptionalFields",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "PutLifecycleConfiguration",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "PutMetricsConfiguration",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "PutObject",
        kind: Kind::Object,
        keys: &[
            "s3:AccessGrantsInstanceArn",
            "s3:ObjectCreationOperation",
            "s3:RequestObjectTag/<key>",
            "s3:RequestObjectTagKeys",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:if-match",
            "s3:if-none-match",
            "s3:object-lock-event-hold",
            "s3:object-lock-event-hold-duration-days",
            "s3:object-lock-legal-hold",
            "s3:object-lock-mode",
            "s3:object-lock-remaining-retention-days",
            "s3:object-lock-retain-until-date",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-acl",
            "s3:x-amz-content-sha256",
            "s3:x-amz-copy-source",
            "s3:x-amz-grant-full-control",
            "s3:x-amz-grant-read",
            "s3:x-amz-grant-read-acp",
            "s3:x-amz-grant-write",
            "s3:x-amz-grant-write-acp",
            "s3:x-amz-metadata-directive",
            "s3:x-amz-object-annotation-directive",
            "s3:x-amz-server-side-encryption",
            "s3:x-amz-server-side-encryption-aws-kms-key-id",
            "s3:x-amz-server-side-encryption-customer-algorithm",
            "s3:x-amz-storage-class",
            "s3:x-amz-website-redirect-location",
        ],
    },
    Action {
        name: "PutObjectAcl",
        kind: Kind::Object,
        keys: &[
            "s3:AccessGrantsInstanceArn",
            "s3:ExistingObjectTag/<key>",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-acl",
            "s3:x-amz-content-sha256",
            "s3:x-amz-grant-full-control",
            "s3:x-amz-grant-read",
            "s3:x-amz-grant-read-acp",
            "s3:x-amz-grant-write",
            "s3:x-amz-grant-write-acp",
            "s3:x-amz-storage-class",
        ],
    },
    Action {
        name: "PutObjectAnnotation",
        kind: Kind::Object,
        keys: &[
            "s3:ExistingObjectTag/<key>",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
            "s3:x-amz-object-if-match",
        ],
    },
    Action {
        name: "PutObjectLegalHold",
        kind: Kind::Object,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:object-lock-legal-hold",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "PutObjectRetention",
        kind: Kind::Object,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:object-lock-event-hold",
            "s3:object-lock-event-hold-duration-days",
            "s3:object-lock-mode",
            "s3:object-lock-remaining-retention-days",
            "s3:object-lock-retain-until-date",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "PutObjectTagging",
        kind: Kind::Object,
        keys: &[
            "s3:ExistingObjectTag/<key>",
            "s3:RequestObjectTag/<key>",
            "s3:RequestObjectTagKeys",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "PutObjectVersionAcl",
        kind: Kind::Object,
        keys: &[
            "s3:AccessGrantsInstanceArn",
            "s3:ExistingObjectTag/<key>",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:versionid",
            "s3:x-amz-acl",
            "s3:x-amz-content-sha256",
            "s3:x-amz-grant-full-control",
            "s3:x-amz-grant-read",
            "s3:x-amz-grant-read-acp",
            "s3:x-amz-grant-write",
            "s3:x-amz-grant-write-acp",
            "s3:x-amz-storage-class",
        ],
    },
    Action {
        name: "PutObjectVersionAnnotation",
        kind: Kind::Object,
        keys: &[
            "s3:ExistingObjectTag/<key>",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:versionid",
            "s3:x-amz-content-sha256",
            "s3:x-amz-object-if-match",
        ],
    },
    Action {
        name: "PutObjectVersionTagging",
        kind: Kind::Object,
        keys: &[
            "s3:ExistingObjectTag/<key>",
            "s3:RequestObjectTag/<key>",
            "s3:RequestObjectTagKeys",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:versionid",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "PutReplicationConfiguration",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:isReplicationPauseRequest",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "ReplicateDelete",
        kind: Kind::Object,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "ReplicateObject",
        kind: Kind::Object,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:object-lock-event-hold",
            "s3:object-lock-event-hold-duration-days",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
            "s3:x-amz-server-side-encryption",
            "s3:x-amz-server-side-encryption-aws-kms-key-id",
            "s3:x-amz-server-side-encryption-customer-algorithm",
        ],
    },
    Action {
        name: "ReplicateObjectAnnotation",
        kind: Kind::Object,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "ReplicateTags",
        kind: Kind::Object,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "RestoreObject",
        kind: Kind::Object,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "TagResource",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "UntagResource",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "UpdateBucketMetadataAnnotationTableConfiguration",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "UpdateBucketMetadataInventoryTableConfiguration",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "UpdateBucketMetadataJournalTableConfiguration",
        kind: Kind::Bucket,
        keys: &[
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
        ],
    },
    Action {
        name: "UpdateObjectEncryption",
        kind: Kind::Object,
        keys: &[
            "s3:ExistingObjectTag/<key>",
            "s3:ResourceAccount",
            "s3:TlsVersion",
            "s3:authType",
            "s3:signatureAge",
            "s3:signatureversion",
            "s3:x-amz-content-sha256",
            "s3:x-amz-server-side-encryption",
            "s3:x-amz-server-side-encryption-aws-kms-key-id",
        ],
    },
];

/// S3's condition keys and their types; a name ending `/<key>` or `/${TagKey}` names a
/// family, one key for each tag key.
pub const KEYS: [(&str, KeyType); 61] = [
    ("s3:AccessGrantScope", KeyType::String),
    ("s3:AccessGrantsInstanceArn", KeyType::Arn),
    ("s3:AccessGrantsLocationScope", KeyType::String),
    ("s3:AccessPointNetworkOrigin", KeyType::String),
    ("s3:AccessPointTag/${TagKey}", KeyType::String),
    ("s3:BucketTag/${TagKey}", KeyType::String),
    ("s3:DataAccessPointAccount", KeyType::String),
    ("s3:DataAccessPointArn", KeyType::Arn),
    ("s3:ExistingJobOperation", KeyType::String),
    ("s3:ExistingJobPriority", KeyType::Numeric),
    ("s3:ExistingObjectTag/<key>", KeyType::String),
    (
        "s3:InventoryAccessibleOptionalFields",
        KeyType::ArrayOfString,
    ),
    ("s3:JobSuspendedCause", KeyType::String),
    ("s3:ObjectCreationOperation", KeyType::Bool),
    ("s3:RequestJobOperation", KeyType::String),
    ("s3:RequestJobPriority", KeyType::Numeric),
    ("s3:RequestObjectTag/<key>", KeyType::String),
    ("s3:RequestObjectTagKeys", KeyType::ArrayOfString),
    ("s3:ResourceAccount", KeyType::String),
    ("s3:TlsVersion", KeyType::Numeric),
    ("s3:annotation-prefix", KeyType::String),
    ("s3:authType", KeyType::String),
    ("s3:delimiter", KeyType::String),
    ("s3:deliverySourceArn", KeyType::Arn),
    ("s3:destinationRegion", KeyType::String),
    ("s3:if-match", KeyType::String),
    ("s3:if-none-match", KeyType::String),
    ("s3:isReplicationPauseRequest", KeyType::Bool),
    ("s3:locationconstraint", KeyType::String),
    ("s3:logType", KeyType::String),
    ("s3:max-annotation-results", KeyType::Numeric),
    ("s3:max-keys", KeyType::Numeric),
    ("s3:object-lock-event-hold", KeyType::String),
    ("s3:object-lock-event-hold-duration-days", KeyType::Numeric),
    ("s3:object-lock-legal-hold", KeyType::String),
    ("s3:object-lock-mode", KeyType::String),
    ("s3:object-lock-remaining-retention-days", KeyType::Numeric),
    ("s3:object-lock-retain-until-date", KeyType::Date),
    ("s3:prefix", KeyType::String),
    ("s3:resourceArnBeingAuthorized", KeyType::Arn),
    ("s3:signatureAge", KeyType::Numeric),
    ("s3:signatureversion", KeyType::String),
    ("s3:versionid", KeyType::String),
    ("s3:x-amz-acl", KeyType::String),
    ("s3:x-amz-bucket-namespace", KeyType::String),
    ("s3:x-amz-content-sha256", KeyType::String),
    ("s3:x-amz-copy-source", KeyType::String),
    ("s3:x-amz-grant-full-control", KeyType::String),
    ("s3:x-amz-grant-read", KeyType::String),
    ("s3:x-amz-grant-read-acp", KeyType::String),
    ("s3:x-amz-grant-write", KeyType::String),
    ("s3:x-amz-grant-write-acp", KeyType::String),
    ("s3:x-amz-metadata-directive", KeyType::String),
    ("s3:x-amz-object-annotation-directive", KeyType::String),
    ("s3:x-amz-object-if-match", KeyType::String),
    ("s3:x-amz-object-ownership", KeyType::String),
    ("s3:x-amz-server-side-encryption", KeyType::String),
    (
        "s3:x-amz-server-side-encryption-aws-kms-key-id",
        KeyType::Arn,
    ),
    (
        "s3:x-amz-server-side-encryption-customer-algorithm",
        KeyType::String,
    ),
    ("s3:x-amz-storage-class", KeyType::String),
    ("s3:x-amz-website-redirect-location", KeyType::String),
];
